### ISSUE TITLE
SDK error: missing class property transform

### ISSUE THREAD

**Issue by vtomasi** [decidim-vocdoni/decidim-module-vocdoni#90]
Hi 
I get the same error on different instances and different servers. Previously I installed the vocdoni module on Decidim 0.27.5 and it worked fine.
I installed the Decidim vocdoni 2.0 module on Decidim 0.28.4 (Ruby 3.1.1 Node v18.20.3,  ENV=production ): the module installs correctly but when I create a new election (new election button) I get an error page.
I get the same error on different instances and different servers. Previously I installed the vocdoni module on Decidim 0.27.5 and it worked fine.

This is the error detected in the log:

ERROR in ./node_modules/@vocdoni/sdk/dist/index.mjs
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/decidim28/decidim-app/node_modules/@vocdoni/sdk/dist/index.mjs: Missing class properties transform.
  78 |
  79 | class ErrAPI extends Error {
> 80 |   raw;
     |   ^^^^
  81 |   constructor(message, error) {
  82 |     super(message ? message : "api error");
  83 |     this.raw = error;
    at File.buildCodeFrameError (/home/decidim28/decidim-app/node_modules/@babel/core/lib/transformation/file/file.js:195:12)
    at NodePath.buildCodeFrameError (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/path/index.js:117:21)
    at pushBody (/home/decidim28/decidim-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:109:20)
    at buildBody (/home/decidim28/decidim-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:90:5)
    at classTransformer (/home/decidim28/decidim-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:512:5)
    at transformClass (/home/decidim28/decidim-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:541:10)
    at PluginPass.ClassExpression (/home/decidim28/decidim-app/node_modules/@babel/plugin-transform-classes/lib/index.js:57:77)
    at newFn (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/visitors.js:172:14)
    at NodePath._call (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/path/context.js:49:20)
    at NodePath.call (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/path/context.js:39:18)
    at NodePath.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/path/context.js:88:31)
    at TraversalContext.visitQueue (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:90:16)
    at TraversalContext.visitSingle (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:66:19)
    at TraversalContext.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:113:19)
    at traverseNode (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/path/context.js:94:52)
    at TraversalContext.visitQueue (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:90:16)
    at TraversalContext.visitMultiple (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:62:17)
    at TraversalContext.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:111:19)
    at traverseNode (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/path/context.js:94:52)
    at TraversalContext.visitQueue (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:90:16)
    at TraversalContext.visitQueue (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:95:21)
    at TraversalContext.visitMultiple (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:62:17)
    at TraversalContext.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:111:19)
    at traverseNode (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/path/context.js:94:52)
    at TraversalContext.visitQueue (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:90:16)
    at TraversalContext.visitSingle (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:66:19)
    at TraversalContext.visit (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/context.js:113:19)
    at traverseNode (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/home/decidim28/decidim-app/node_modules/@babel/traverse/lib/index.js:53:34)
    at transformFile (/home/decidim28/decidim-app/node_modules/@babel/core/lib/transformation/index.js:80:31)
    at transformFile.next (<anonymous>)
    at run (/home/decidim28/decidim-app/node_modules/@babel/core/lib/transformation/index.js:25:12)
    at run.next (<anonymous>)
    at transform (/home/decidim28/decidim-app/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/home/decidim28/decidim-app/node_modules/gensync/index.js:261:32)
    at /home/decidim28/decidim-app/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/decidim28/decidim-app/node_modules/gensync/index.js:223:11)
 @ ../.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/decidim-module-vocdoni-d0ce3fa53fa0/app/packs/src/decidim/vocdoni/voter/new-vote.js 1:8496-8554 22:331-347 22:523-545 22:608-622 26:844-860 31:255-294
 @ ../.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/decidim-module-vocdoni-d0ce3fa53fa0/app/packs/entrypoints/decidim_vocdoni_voter_new-vote.js 1:0-43

webpack 5.96.1 compiled with 1 error in 76599 ms
decidim28@meet:~/decidim-xxxxxx$ npm install core-js regenerator-runtime @babel/plugin-proposal-class-properties babel-plugin-transform-class-properties --save-dev
⠇^Z
[1]+  Stopped                 npm install core-js regenerator-runtime @babel/plugin-proposal-class-properties babel-plugin-transform-class-properties --save-dev

**Comment by fblupi** [comment]
You just need to include `"@babel/plugin-proposal-class-properties"` in the plugins inside your `babel.config.json` file.

**Comment by vtomasi** [comment]
> You just need to include `"@babel/plugin-proposal-class-properties"` in the plugins inside your `babel.config.json` file.

I had already tried but it still didn't work even with a different error.
But I discovered  now that in babel.config.json:

this configuration doesn't work

"plugins": [
    @babel/plugin-transform-classes",
    "@babel/plugin-proposal-class-properties",
    [

when I reversed the strings so now it works correctly
 
 "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-classes",
    [

Thanks again.

Vittorio
